#!/usr/bin/python3

import sys
import pprint
import optparse
import decimal

import Components
import KiCadExportParser
import Octopart
import Filter

def parseOptions():
    global options
    global netlist_filenames

    parser = optparse.OptionParser(usage="%prog --octopart-apikey=<apikey> <netlist.xml> ...")
    parser.add_option("--octopart-apikey", dest="octopart_apikey")
    parser.add_option("--quantity", dest="quantity", type="int", default="1")
    parser.add_option("--USD2EUR", dest="USD2EUR")

    (options, netlist_filenames) = parser.parse_args()

def main():
    parseOptions()

    components = Components.Components()
    for netlist_filename in netlist_filenames:
        p = KiCadExportParser.KiCadExportParser(netlist_filename)
        components.merge(p.components)

    octopart = Octopart.Octopart(options.octopart_apikey)

    filter = Filter.Filter()
    filter.currencies["EUR"] = decimal.Decimal("1.0")
    if options.USD2EUR:
        filter.currencies["USD"] = decimal.Decimal(options.USD2EUR)

    components.findParts(catalogue=octopart, filter=filter)

    components.findBestOffers(nrProducts=options.quantity)


    shopping_list = components.shoppingList(nrProducts=options.quantity)

    open("shopping_list.csv", "w").write(shopping_list)

if __name__ == "__main__":
    main()
